config/routes.rb
OnlineStore::Application.routes.draw do

  resources :comments

  devise_for :users, :skip => :registrations

  resources :orders

  resources :line_items

  resources :line_items do
    put 'decrease', on: :member
    resources :carts
  end
  
  match "/category" => "products#category"

  resources :carts

  resources :products

  root :to => "store#index", as: 'store'

  match "*path" => 'error#handle404'

end

app/models/product.rb
class Product < ActiveRecord::Base

  paginates_per 9
  
  has_many :line_items
  has_many :comments, :dependent => :destroy

  before_destroy :ensure_empty
  mount_uploader :image_url, ImageUrlUploader

  attr_accessible :description, :image_url, :price, :title, :category, :id
  validates :description, :image_url, :price, :title, :category, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.0}
  validates_presence_of :image_url

  def ensure_empty
    line_items.empty?
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_filter :authenticate_user!, :only => [:index, :new, :create, :edit, :update]
  before_filter :find, :only => [:show, :edit, :destroy, :update]

  def find
    @product = Product.find(params[:id])
  end
    
  def index
    @products = Product.order(:title).page params[:page]
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end


  def show
    @comment = Comment.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
      format.js
    end
  end

  def new
    @product = Product.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  def edit
  end

  def create
    @product = Product.new(params[:product])
    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created, location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def category
    @selected = Product.find_all_by_category(params[:category])
    @products = Kaminari.paginate_array(@selected).page(params[:page])
    render action: "index"
  end  

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows: 6 %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.file_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/comment.js.erb
$(".button-style").click(function(){ 
  this.fadeOut();
 });

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<h1>For Salesmen</h1>
<br>
  
  <% @products.each do |product| %>
    <div class="list_items">
      <div class="prod_image">
        <%= image_tag(product.image_url) %>
      </div>
          <h3><%= product.title %></h3>
          
          <%= truncate(strip_tags(product.description), length: 80) %>
        <%= link_to "Show", product %>
        <%= link_to "Edit", edit_product_path(product) %>
        <%= link_to "Destroy", product, confirm: "You sure?", method: :delete %>

    </div>
    <%end%>

  <%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>



<div class="show_image">
  <%= image_tag @product.image_url %>
</div>

<div class="description_item">

<div class="show_item_holder">
<p>
  <h1><%= @product.title %></h1>
</p>
<b>Description:</b>
  <%= @product.description %>
</div>
<p class="list_price">
  <%= "$#{@product.price}" %>
</p>
<%= link_to 'Back', products_path, class: "button-style" %>
</div>

<br>



<div class="show_comments">
  <% @product.comments.reverse.each do |comment| %>
    <ul>
      <li><p><b><%= comment.nickname %></b>:</p></li>
      <li><p><%= comment.content %></p></li>
      <li><p><%= comment.created_at %></p></li>
      <% if current_user && current_user.admin? %>
      <tr>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
      
    </ul>
  <% end %>  
</div> 

<div class="on_off">
  <%= link_to "Leave comment", remote: true %>
</div>
 

<div>
  <%= render "comments/form" %>
</div>  

app/views/products/show.js.erb
$('.on_off a').click(function() { 
  $(".new_comment").toggle();
  this.hide();
});