config/routes.rb
OnlineStore::Application.routes.draw do

  resources :comments

  devise_for :users, :skip => :registrations

  resources :orders

  resources :line_items

  resources :line_items do
    put 'decrease', on: :member
    resources :carts
  end
  
  match "/category" => "products#category"

  resources :carts

  resources :products

  root :to => "store#index", as: 'store'

  match "*path" => 'error#handle404'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  attr_accessible :cart_id, :product_id, :quantity
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    product.price * quantity
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  
  before_filter :find_line_item, :only => [:show, :destroy, :update]

  def find_line_item
    @line_item = LineItem.find(params[:id])
  end  

  def index
    @line_items = LineItem.order(:title)
  end

  def decrease 
    @cart = current_cart
    @line_item = @cart.decrease_line_item_quantity(params[:id])
    respond_to do |format|
      if @line_item.save
        format.html { redirect_to store_path, notice: 'Line item was successfully updated.' }
        format.js {@current_item = @line_item}
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.js {@current_item = @line_item}
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  # GET /line_items/new
  # GET /line_items/new.json
  def new
    @line_item = LineItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @line_item }
    end
  end

  def create
    @cart = current_cart
    product = Product.find(params[:product_id])
    @line_item = @cart.add_product(product.id) if product.price > 0
    respond_to do |format|
      format.js { @current_item = @line_item } if @line_item.save
    end
  end

  def update
    respond_to do |format|
      if @line_item.update_attributes(params[:line_item])
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
      format.js
    end

  end

end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>
  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br />
    <%= f.text_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :cart_id %><br />
    <%= f.number_field :cart_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<% if @line_item == @current_item %>
  <tr id="current_item">
<% else  %>
  <tr>
<% end %>
  <td><%= link_to "[X]", decrease_line_item_path(line_item), method: :put, remote: true %></td>
  <td><%= line_item.product.title %></td>
  <td><%= line_item.quantity %>&times</td>
  <td><%= number_to_currency(line_item.total_price) %></td>
</tr>

app/views/line_items/create.js.erb
$("#nottice").hide();


$('.cart2').html("<%=j render @cart  %>");

$('.total').css({'background-color':'#FFFF00'}).animate({'background-color':'#FFFFFF'}, 1000);




if ($('.cart2 table tr').length <= 1){
  $('.cart2').hide();

}

if ($('.cart2 table tr').length >= 2){
  $('.cart2').css(".shadow");
}

app/views/line_items/decrease.js.erb
$('.cart2').html('<%=j render @cart %>');
$('.total').css({'background-color':'#33FF99'}).animate({'background-color':'#ffffff'}, 1000);

app/views/line_items/destroy.js.erb
$(".cart2").remove();

app/views/line_items/edit.html.erb
<h1>Editing line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @line_item %> |
<%= link_to 'Back', line_items_path %>

app/views/line_items/index.html.erb
<h1>Listing line_items</h1>

<table>
  <tr>
    <th>Product</th>
    <th>Cart</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @line_items.each do |line_item| %>
  <tr>
    <td><%= line_item.product_id %></td>
    <td><%= line_item.cart_id %></td>
    <td><%= link_to 'Show', line_item %></td>
    <td><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
    <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Line item', new_line_item_path %>

app/views/line_items/new.html.erb
<h1>New line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', line_items_path %>

app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Product:</b>
  <%= @line_item.product_id %>
</p>

<p>
  <b>Cart:</b>
  <%= @line_item.cart_id %>
</p>


<%= link_to 'Edit', edit_line_item_path(@line_item) %> |
<%= link_to 'Back', line_items_path %>